### ISSUE TITLE
demo and blog post gone?

### ISSUE THREAD

**Issue by yankeeinlondon** [node-vision/node-react-xero-app#3]
Was very excited to see a modern working example but sadly it appears the blog post and demo are no longer up (I'm getting a 502 error)?

**Comment by romanmandryk** [comment]
Thanks for notifying me.
It should be back online. Feel free to close the issue if it works for you.

**Comment by yankeeinlondon** [comment]
Yes it's back up. Many thanks for the quick response.

**Comment by tratefan** [comment]
Hi, is the demo offline?
